name: "Validate Gradle Wrapper"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - master

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: gradle/wrapper-validation-action@v1
      - run: |
              gradle build  
              gradle test
              pwd
              ls -l
              cd build
              pwd
              ls -l
              cd libs
              java -jar gradle-simple.jar
